AWSTemplateFormatVersion: '2010-09-09'
Description:  This template deploys a VPC, ALB and IAM, with a pair of public and private subnets spread
  across two Availability Zones. It deploys an internet gateway, with a default
  route on the public subnets. It deploys a pair of NAT gateways (one in each AZ),
  and default routes for them in the private subnets.

Parameters:
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24

  ApplicationName:
    Description: An environment name that is prefixed to resource names
    Type: String

  DepRegion:
    Description: Region used for deployment
    Type: String

  ToolsAccount:
    Description: AWS AccountNumber for Tools Account
    Type: Number

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "vpc.yaml"
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "alb.yaml"
      Parameters:
        ApplicationName: !Ref ApplicationName
    DependsOn: VPCStack
    
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "iam.yaml"
      Parameters:
        ApplicationName: !Ref ApplicationName
        DepRegion: !Ref DepRegion
        ToolsAccount: !Ref ToolsAccount