version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build command"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
  - '**/*'
